#------------------------------------------------------------
#|                                                          |
#|      _  _______        __     __    _____   ____         |
#|     | ||___ ___|      |  \   /  |  / ____| |  _ \        |
#|     | |   | |   ___   | |\\ //| | | (___   | | \ \       |
#|     | |   | |  / _ \  | | \_/ | |  \___ \  | |  ) )      |
#|     | |   | | | (_) | | |     | |  ____) | | |_/ /       |
#|     |_|   |_|  \___/  |_|     |_| |_____/  |____/        |
#|                                                          |
#|                                                          |
#------------------------------------------------------------
#|                 +==================+                     |
#|                 |    NightVision   |                     |
#|                 |------------------|                     |
#|                 |        1.0       |                     |
#|                 |------------------|                     |
#|                 |  PolsatGraniePL  |                     |
#|                 +==================+                     |
#------------------------------------------------------------
#
# Hello, if you need help or have an idea that will improve our plugin,
#                   then be sure to contact us:
#
#  IToMSD Website: https://itomsd.com/
#  IToMSD Discord: https://dc.itomsd.com/
#  IToMSD SpigotMC: https://www.spigotmc.org/resources/authors/itomsd.1983449/




# Messages

messages:
  nightvision_enabled: '&aNight vision enabled.'
  nightvision_disabled: '&cNight vision disabled.'
  no_permission: "You do not have permission to use this command."
  no_permission_reload: '&cYou do not have permission to reload the configuration.'
  plugin_reloaded: "&aPlugin reloaded."